# Generated by Django 3.0.5 on 2020-04-22 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200422_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='producer',
        ),
        migrations.AddField(
            model_name='track',
            name='producers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracks.Producer'),
        ),
    ]
